name: pancakeswapv2
networks:
- id: 56
  start_block: 0
  end_block: null
  contracts:
  - name: PancakeFactory
    address:
    - 0xcA143Ce32Fe78f1f7019d7d551a6402fC5350c73
    handler: ./src/EventHandlers.js
    events:
    - event: PairCreated(address indexed token0, address indexed token1, address pair, uint256 )
